<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <BaseOutputPath></BaseOutputPath>
    <Title>TestApplication</Title>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\Icons\ArrowBlueLeft.png" />
    <None Remove="Images\Icons\ArrowBlueLeftActive.png" />
    <None Remove="Images\Icons\ArrowBlueLeftInactive.png" />
    <None Remove="Images\Icons\ArrowBlueRightInactive.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Panels\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WpfDockManager\WpfDockingManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Icons\ArrowBlueLeftActive.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Icons\ArrowBlueLeftInactive.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Icons\ArrowBlueRightActive.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Icons\ArrowBlueRightInactive.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
